### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by xCyborg** [MarcinODev/Shader-Unity-Support#1]
Hi, will there be an update to add VS 16 compatibility soon?

**Comment by MarcinODev** [comment]
Hi, it's hard to say when because it's related to which VS I use in current project. Have you tried to compile it for vs 2019? Probably it will just work or require small fixes.

**Comment by DesigningKnights** [comment]
How to compile it exactly?  I installed the support for VSIX, but dont know how to make this work in VS2019

**Comment by MarcinODev** [comment]
You need open ShaderUnitySupportVS.sln and click Run/Compile button. It should "just" work. Also when I put this plugin for store I use Release configuration but Debug also works.
Of course there can be some compilation errors for differences between 2017 and 2019 but this you need to check by your own (or wait till I move to 2019 with this project).
